language: zh-tw
# Header
menu:
  Home: /
  Archives: /archives
# rss: /atom.xml

# Content
excerpt_link: "繼續看下去 \u23E9"
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
# - tag
- tagcloud
# - archive
- recent_posts
- recent_comment
- links

links:
  "小助助的精神實驗室": //ichi1234567.github.com/
  "Yy's Program": //yy-programer.blogspot.tw/
  "Yy's BLOG": //yy-blogger.blogspot.tw/

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-34931132-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
